import type { IFactureFacturX } from '@/types';

export const MOCK_FACTURES_FACTURX: IFactureFacturX[] = [
  {
    id: 'fac-001',
    numero: 'FAC-2026-001',
    copropriete: 'Résidence Les Pins',
    fournisseur: 'Chauffage Pro SARL',
    montantTTC: 4200,
    date: '2026-04-01',
    statutPaiement: 'PAYEE',
    statutFacturX: 'GENERE',
    dateGeneration: '2026-04-02',
    profil: 'EN16931',
  },
  {
    id: 'fac-002',
    numero: 'FAC-2026-002',
    copropriete: 'Immeuble Voltaire',
    fournisseur: 'EcoThermie SAS',
    montantTTC: 1850,
    date: '2026-04-05',
    statutPaiement: 'EN_ATTENTE',
    statutFacturX: 'EN_ATTENTE',
    profil: 'EN16931',
  },
  {
    id: 'fac-003',
    numero: 'FAC-2026-003',
    copropriete: 'Les Jardins du Lac',
    fournisseur: 'VerdurePaysage',
    montantTTC: 3600,
    date: '2026-04-08',
    statutPaiement: 'EN_ATTENTE',
    statutFacturX: 'EN_ATTENTE',
    profil: 'EN16931',
  },
  {
    id: 'fac-004',
    numero: 'FAC-2025-198',
    copropriete: 'Résidence Berlioz',
    fournisseur: 'Électricité Batiment',
    montantTTC: 920,
    date: '2025-12-15',
    statutPaiement: 'PAYEE',
    statutFacturX: 'NON_APPLICABLE',
    profil: 'MINIMUM',
  },
  {
    id: 'fac-005',
    numero: 'FAC-2026-004',
    copropriete: 'Résidence Les Pins',
    fournisseur: 'Ascenseurs Rhône-Alpes',
    montantTTC: 12400,
    date: '2026-04-10',
    statutPaiement: 'EN_RETARD',
    statutFacturX: 'EN_ATTENTE',
    profil: 'EN16931',
  },
];
