import type { IPPTCopropriete } from '@/types';
import { TravauxPrevisionnelStatut, TypeTravauxPrevisionnel } from '@/types/enums';

export const MOCK_PPT_COPROPRIETES: IPPTCopropriete[] = [
  {
    coproprieteId: 'copro-1',
    nom: 'Résidence Les Pins',
    nbLots: 32,
    derniereMAJ: '2026-03-15',
    travaux: [
      {
        id: 'trav-1',
        titre: 'Ravalement de façade',
        type: TypeTravauxPrevisionnel.FACADE,
        datePrevisionnelle: '2027-06-01',
        montantEstime: 85000,
        montantVote: 87500,
        statut: TravauxPrevisionnelStatut.VOTE,
        priorite: 'HAUTE',
        description: "Ravalement complet avec isolation par l'extérieur",
        etapes: [
          { id: 'e1', label: 'Devis', date: '2026-09-15', statut: 'FAIT', montant: 87500 },
          { id: 'e2', label: 'Vote en AG', date: '2026-11-20', statut: 'FAIT' },
          { id: 'e3', label: 'Commande', date: '2027-02-01', statut: 'EN_COURS' },
          { id: 'e4', label: 'Intervention', statut: 'A_VENIR' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
      {
        id: 'trav-2',
        titre: 'Remplacement chaudière collective',
        type: TypeTravauxPrevisionnel.CHAUFFAGE,
        datePrevisionnelle: '2026-10-01',
        montantEstime: 42000,
        statut: TravauxPrevisionnelStatut.EN_COURS,
        priorite: 'CRITIQUE',
        etapes: [
          { id: 'e1', label: 'Devis', date: '2026-01-10', statut: 'FAIT', montant: 41800 },
          { id: 'e2', label: 'Vote en AG', date: '2026-02-14', statut: 'FAIT' },
          { id: 'e3', label: 'Commande', date: '2026-03-01', statut: 'FAIT' },
          { id: 'e4', label: 'Intervention', date: '2026-10-01', statut: 'EN_COURS' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
      {
        id: 'trav-3',
        titre: 'Étanchéité toiture terrasse',
        type: TypeTravauxPrevisionnel.ETANCHEITE,
        datePrevisionnelle: '2028-04-01',
        montantEstime: 28000,
        statut: TravauxPrevisionnelStatut.PREVU,
        priorite: 'NORMALE',
        etapes: [
          { id: 'e1', label: 'Devis', statut: 'A_VENIR' },
          { id: 'e2', label: 'Vote en AG', statut: 'A_VENIR' },
          { id: 'e3', label: 'Commande', statut: 'A_VENIR' },
          { id: 'e4', label: 'Intervention', statut: 'A_VENIR' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
      {
        id: 'trav-4',
        titre: 'Mise aux normes ascenseur',
        type: TypeTravauxPrevisionnel.ASCENSEUR,
        datePrevisionnelle: '2029-01-01',
        montantEstime: 35000,
        statut: TravauxPrevisionnelStatut.A_L_ETUDE,
        priorite: 'NORMALE',
        etapes: [
          { id: 'e1', label: 'Devis', statut: 'A_VENIR' },
          { id: 'e2', label: 'Vote en AG', statut: 'A_VENIR' },
          { id: 'e3', label: 'Commande', statut: 'A_VENIR' },
          { id: 'e4', label: 'Intervention', statut: 'A_VENIR' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
      {
        id: 'trav-5',
        titre: 'Réfection parkings souterrains',
        type: TypeTravauxPrevisionnel.AUTRE,
        datePrevisionnelle: '2025-08-01',
        dateRealisation: '2025-09-15',
        montantEstime: 18000,
        montantReel: 17400,
        statut: TravauxPrevisionnelStatut.TERMINE,
        priorite: 'NORMALE',
        etapes: [
          { id: 'e1', label: 'Devis', date: '2025-02-01', statut: 'FAIT', montant: 17400 },
          { id: 'e2', label: 'Vote en AG', date: '2025-03-10', statut: 'FAIT' },
          { id: 'e3', label: 'Commande', date: '2025-04-01', statut: 'FAIT' },
          { id: 'e4', label: 'Intervention', date: '2025-08-01', statut: 'FAIT' },
          { id: 'e5', label: 'Réception', date: '2025-09-15', statut: 'FAIT' },
        ],
      },
    ],
  },
  {
    coproprieteId: 'copro-2',
    nom: 'Immeuble Voltaire',
    nbLots: 18,
    derniereMAJ: '2026-01-20',
    travaux: [
      {
        id: 'trav-6',
        titre: "Peinture cage d'escalier",
        type: TypeTravauxPrevisionnel.AUTRE,
        datePrevisionnelle: '2026-07-01',
        montantEstime: 12000,
        statut: TravauxPrevisionnelStatut.VOTE,
        priorite: 'FAIBLE',
        etapes: [
          { id: 'e1', label: 'Devis', date: '2026-02-01', statut: 'FAIT', montant: 11800 },
          { id: 'e2', label: 'Vote en AG', date: '2026-03-15', statut: 'FAIT' },
          { id: 'e3', label: 'Commande', statut: 'A_VENIR' },
          { id: 'e4', label: 'Intervention', statut: 'A_VENIR' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
      {
        id: 'trav-7',
        titre: 'Remplacement menuiseries',
        type: TypeTravauxPrevisionnel.FACADE,
        datePrevisionnelle: '2030-01-01',
        montantEstime: 65000,
        statut: TravauxPrevisionnelStatut.A_L_ETUDE,
        priorite: 'NORMALE',
        etapes: [
          { id: 'e1', label: 'Devis', statut: 'A_VENIR' },
          { id: 'e2', label: 'Vote en AG', statut: 'A_VENIR' },
          { id: 'e3', label: 'Commande', statut: 'A_VENIR' },
          { id: 'e4', label: 'Intervention', statut: 'A_VENIR' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
    ],
  },
  {
    coproprieteId: 'copro-3',
    nom: 'Les Jardins du Lac',
    nbLots: 65,
    derniereMAJ: '2026-04-01',
    travaux: [
      {
        id: 'trav-8',
        titre: 'Rénovation espaces verts',
        type: TypeTravauxPrevisionnel.ESPACES_VERTS,
        datePrevisionnelle: '2026-05-01',
        montantEstime: 22000,
        statut: TravauxPrevisionnelStatut.EN_COURS,
        priorite: 'NORMALE',
        etapes: [
          { id: 'e1', label: 'Devis', date: '2026-01-15', statut: 'FAIT', montant: 21500 },
          { id: 'e2', label: 'Vote en AG', date: '2026-02-20', statut: 'FAIT' },
          { id: 'e3', label: 'Commande', date: '2026-03-10', statut: 'FAIT' },
          { id: 'e4', label: 'Intervention', date: '2026-05-01', statut: 'EN_COURS' },
          { id: 'e5', label: 'Réception', statut: 'A_VENIR' },
        ],
      },
    ],
  },
  {
    coproprieteId: 'copro-4',
    nom: 'Résidence Berlioz',
    nbLots: 12,
    derniereMAJ: '2026-02-10',
    travaux: [],
  },
];
