import type { IDPE } from '@/types';

export const MOCK_DPE_LIST: IDPE[] = [
  {
    id: 'dpe-1',
    coproprieteId: 'copro-1',
    coproprieteNom: 'Résidence Les Pins',
    nbLots: 32,
    classeEnergie: 'D',
    classeGES: 'D',
    dateDiagnostic: '2023-06-15',
    dateExpiration: '2033-06-15',
    diagnostiqueur: 'Cabinet Thermique Conseil',
    numeroADEME: '2306150001',
    consoEnergie: 215,
    emissionsGES: 48,
    statut: 'VALIDE',
    travauxRecommandes: [],
    historique: [
      { id: 'h1', dateDiagnostic: '2018-04-10', classeEnergie: 'E', diagnostiqueur: 'DiagExpert PACA' },
    ],
  },
  {
    id: 'dpe-2',
    coproprieteId: 'copro-2',
    coproprieteNom: 'Immeuble Voltaire',
    nbLots: 18,
    classeEnergie: 'F',
    classeGES: 'F',
    dateDiagnostic: '2020-09-20',
    dateExpiration: '2026-09-20',
    diagnostiqueur: 'EcoThermie SAS',
    numeroADEME: '2009200042',
    consoEnergie: 375,
    emissionsGES: 84,
    statut: 'EXPIRE_BIENTOT',
    travauxRecommandes: [],
    historique: [
      { id: 'h2', dateDiagnostic: '2015-11-03', classeEnergie: 'F', diagnostiqueur: 'EcoThermie SAS' },
    ],
  },
  {
    id: 'dpe-3',
    coproprieteId: 'copro-3',
    coproprieteNom: 'Les Jardins du Lac',
    nbLots: 65,
    classeEnergie: 'C',
    classeGES: 'C',
    dateDiagnostic: '2024-03-01',
    dateExpiration: '2034-03-01',
    diagnostiqueur: 'Diagnotec Île-de-France',
    numeroADEME: '2403010088',
    consoEnergie: 145,
    emissionsGES: 32,
    statut: 'VALIDE',
    travauxRecommandes: [],
    historique: [],
  },
  {
    id: 'dpe-4',
    coproprieteId: 'copro-4',
    coproprieteNom: 'Résidence Berlioz',
    nbLots: 12,
    classeEnergie: 'G',
    classeGES: 'G',
    dateDiagnostic: '2019-01-10',
    dateExpiration: '2025-01-10',
    diagnostiqueur: 'Cabinet Immo Diag',
    numeroADEME: '1901100005',
    consoEnergie: 510,
    emissionsGES: 115,
    statut: 'EXPIRE',
    travauxRecommandes: [],
    historique: [
      { id: 'h3', dateDiagnostic: '2012-07-22', classeEnergie: 'G', diagnostiqueur: 'Cabinet Immo Diag' },
    ],
  },
];
