'use client';

/**
 * Service de gestion des réunions à distance
 * V1: Génération de liens Jitsi (pas d'OAuth nécessaire)
 *
 * Architecture prévue pour OAuth future:
 * - Interface RemoteMeetingProvider
 * - Implémentations: JitsiProvider, ZoomProvider, GoogleMeetProvider, TeamsProvider
 */

import { createClient } from '@/lib/supabase/client';

// Helper: Create untyped client for tables/views not yet in generated types
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const createUntypedClient = () => createClient() as any;

// ============================================================================
// Types
// ============================================================================

export type RemoteMeetingProvider = 'jitsi' | 'zoom' | 'meet' | 'teams' | 'webex' | 'other';

export interface CreateRemoteMeetingInput {
  /** ID de la copropriété */
  coproId: string;
  /** ID de l'AG */
  agId: string;
  /** Titre de la réunion (utilisé pour générer le room name) */
  title: string;
  /** Date/heure de début (ISO string) */
  startsAt: string;
  /** Date/heure de fin optionnelle (ISO string) */
  endsAt?: string;
  /** Provider préféré (défaut: jitsi) */
  provider?: RemoteMeetingProvider;
}

export interface RemoteMeetingResult {
  /** Provider utilisé */
  provider: RemoteMeetingProvider;
  /** URL de la réunion */
  url: string;
  /** Nom/ID de la room */
  roomName: string;
  /** Indique si c'est un lien auto-généré ou externe */
  autoGenerated: boolean;
}

export interface SavedRemoteMeeting extends RemoteMeetingResult {
  /** ID de l'AG */
  agId: string;
  /** Date de création */
  createdAt: string;
}

// ============================================================================
// Jitsi Provider (V1 - Pas d'OAuth)
// ============================================================================

const JITSI_BASE_URL = 'https://meet.jit.si';

/**
 * Génère un nom de room Jitsi unique et lisible
 */
function generateJitsiRoomName(coproId: string, agId: string, title: string): string {
  // Nettoyer le titre pour créer un slug
  const slug = title
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // Supprimer accents
    .replace(/[^a-z0-9]+/g, '-') // Remplacer caractères spéciaux
    .replace(/^-+|-+$/g, '') // Supprimer tirets début/fin
    .substring(0, 30); // Limiter longueur

  // Ajouter un hash court pour unicité
  const hash = agId.substring(0, 8);

  return `coproflex-${slug}-${hash}`;
}

/**
 * Crée un lien Jitsi Meet
 */
function createJitsiMeeting(input: CreateRemoteMeetingInput): RemoteMeetingResult {
  const roomName = generateJitsiRoomName(input.coproId, input.agId, input.title);
  const url = `${JITSI_BASE_URL}/${roomName}`;

  return {
    provider: 'jitsi',
    url,
    roomName,
    autoGenerated: true,
  };
}

// ============================================================================
// Provider Detection
// ============================================================================

/**
 * Détecte le provider à partir d'une URL de réunion
 */
export function detectProviderFromUrl(url: string): RemoteMeetingProvider {
  if (!url) return 'other';

  const urlLower = url.toLowerCase();

  if (urlLower.includes('zoom.us') || urlLower.includes('zoom.com')) {
    return 'zoom';
  }
  if (urlLower.includes('meet.google.com')) {
    return 'meet';
  }
  if (urlLower.includes('teams.microsoft.com') || urlLower.includes('teams.live.com')) {
    return 'teams';
  }
  if (urlLower.includes('webex.com')) {
    return 'webex';
  }
  if (urlLower.includes('meet.jit.si') || urlLower.includes('jitsi')) {
    return 'jitsi';
  }

  return 'other';
}

/**
 * Labels affichables pour les providers
 */
export const PROVIDER_LABELS: Record<RemoteMeetingProvider, string> = {
  jitsi: 'Jitsi Meet',
  zoom: 'Zoom',
  meet: 'Google Meet',
  teams: 'Microsoft Teams',
  webex: 'Cisco Webex',
  other: 'Visioconférence',
};

// ============================================================================
// Main Service Functions
// ============================================================================

/**
 * Crée une réunion à distance pour une AG
 *
 * @param input Paramètres de création
 * @returns Résultat avec URL et provider
 *
 * @example
 * const meeting = await createRemoteMeeting({
 *   coproId: 'xxx',
 *   agId: 'yyy',
 *   title: 'AG Ordinaire 2026',
 *   startsAt: '2026-04-15T19:00:00',
 * });
 * // meeting.url = 'https://meet.jit.si/coproflex-ag-ordinaire-2026-yyy12345'
 */
export async function createRemoteMeeting(
  input: CreateRemoteMeetingInput
): Promise<RemoteMeetingResult> {
  const provider = input.provider || 'jitsi';

  // V1: Seul Jitsi est supporté (pas d'OAuth)
  // Futur: switch sur provider pour appeler l'API appropriée
  switch (provider) {
    case 'jitsi':
      return createJitsiMeeting(input);

    // TODO: Implémenter avec OAuth
    case 'zoom':
    case 'meet':
    case 'teams':
    case 'webex':
      // Provider requires OAuth, falling back to Jitsi
      return createJitsiMeeting(input);

    default:
      return createJitsiMeeting(input);
  }
}

/**
 * Sauvegarde le lien de réunion dans la base de données (ag_meetings)
 */
export async function saveRemoteMeetingToAg(
  agId: string,
  coproId: string,
  meeting: RemoteMeetingResult
): Promise<boolean> {
  const supabase = createUntypedClient();

  const { error } = await supabase
    .from('ag_meetings')
    .update({
      remote_meeting_url: meeting.url,
      remote_meeting_provider: meeting.provider,
    })
    .eq('id', agId)
    .eq('copro_id', coproId);

  if (error) {
    console.error('[remote-meeting] Error saving to DB:', error);
    return false;
  }

  return true;
}

/**
 * Récupère le lien de réunion existant pour une AG
 */
export async function getRemoteMeetingFromAg(
  agId: string
): Promise<SavedRemoteMeeting | null> {
  const supabase = createUntypedClient();

  const { data, error } = await supabase
    .from('ag_meetings')
    .select('id, remote_meeting_url, remote_meeting_provider, created_at')
    .eq('id', agId)
    .single();

  if (error || !data?.remote_meeting_url) {
    return null;
  }

  return {
    agId: data.id,
    url: data.remote_meeting_url,
    provider: data.remote_meeting_provider || 'other',
    roomName: extractRoomName(data.remote_meeting_url),
    autoGenerated: data.remote_meeting_url.includes('meet.jit.si/coproflex-'),
    createdAt: data.created_at,
  };
}

/**
 * Extrait le nom de room d'une URL de réunion
 */
function extractRoomName(url: string): string {
  try {
    const urlObj = new URL(url);
    return urlObj.pathname.replace(/^\/+/, '');
  } catch {
    return url;
  }
}

/**
 * Crée et sauvegarde une réunion à distance en une seule opération (idempotent)
 * Ne recrée pas le lien s'il existe déjà
 */
export async function ensureRemoteMeeting(
  input: CreateRemoteMeetingInput
): Promise<RemoteMeetingResult> {
  // Vérifier si un lien existe déjà
  const existing = await getRemoteMeetingFromAg(input.agId);
  if (existing) {
    return {
      provider: existing.provider,
      url: existing.url,
      roomName: existing.roomName,
      autoGenerated: existing.autoGenerated,
    };
  }

  // Créer un nouveau lien
  const meeting = await createRemoteMeeting(input);

  // Sauvegarder en DB
  await saveRemoteMeetingToAg(input.agId, input.coproId, meeting);

  return meeting;
}

/**
 * Supprime le lien de réunion d'une AG
 */
export async function removeRemoteMeetingFromAg(
  agId: string,
  coproId: string
): Promise<boolean> {
  const supabase = createUntypedClient();

  const { error } = await supabase
    .from('ag_meetings')
    .update({
      remote_meeting_url: null,
      remote_meeting_provider: null,
    })
    .eq('id', agId)
    .eq('copro_id', coproId);

  if (error) {
    console.error('[remote-meeting] Error removing from DB:', error);
    return false;
  }

  return true;
}
